// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBannerFields {
  /** Title */
  title: string;

  /** Sub Title */
  subTitle: string;

  /** Background */
  background?: Record<string, any> | undefined;

  /** Link */
  link?: INavigationLink | undefined;

  /** Secondary Link */
  secondaryLink?: INavigationLink | undefined;
}

/** A Banner to go at the top of a page */

export interface IBanner extends Entry<IBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "banner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image: Record<string, any>;

  /** Content */
  content?: Document | undefined;
}

/** A basic page for the site */

export interface IBlog extends Entry<IBlogFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blog";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICardFields {
  /** Title */
  title: string;

  /** Icon */
  icon: Record<string, any>;

  /** Text */
  text?: string | undefined;
}

export interface ICard extends Entry<ICardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "card";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICardListingFields {
  /** Title */
  title: string;

  /** Introduction */
  introduction?: string | undefined;

  /** Cards */
  cards: ICard[];
}

export interface ICardListing extends Entry<ICardListingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "cardListing";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICarouselFields {
  /** Title */
  title: string;

  /** Headline */
  headline?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Items */
  items?: IEvent | IFacility | ITraining | IPerson | undefined;
}

/** An automatic rotating carousel of slides */

export interface ICarousel extends Entry<ICarouselFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "carousel";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEventFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image: Record<string, any>;

  /** Content */
  content?: Document | undefined;

  /** slug */
  slug: string;
}

/** A scheduled event for the pony club. */

export interface IEvent extends Entry<IEventFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "event";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEventListingFields {
  /** Title */
  title: string;
}

export interface IEventListing extends Entry<IEventListingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "eventListing";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFacilityFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Content */
  content?: Document | undefined;

  /** Image */
  image: Record<string, any>;

  /** slug */
  slug: string;
}

/** A facility available at the pony club, i.e. club rooms haha :-) */

export interface IFacility extends Entry<IFacilityFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "facility";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFacilityListingFields {
  /** Title */
  title?: string | undefined;
}

export interface IFacilityListing extends Entry<IFacilityListingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "facilityListing";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFooterFields {
  /** Title */
  title: string;

  /** Logo */
  logo: Record<string, any>;

  /** Menu */
  menu: IMenu;

  /** Address */
  address?: string | undefined;

  /** Copyright */
  copyright: string;

  /** Bottom Links */
  bottomLinks: INavigationLink[];

  /** Right Column */
  rightColumn?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;
}

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMenuFields {
  /** Title */
  title: string;

  /** Links */
  links: INavigationLink[];

  /** Logo */
  logo?: Record<string, any> | undefined;
}

export interface IMenu extends Entry<IMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "menu";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INavigationLinkFields {
  /** Title */
  title: string;

  /** Page */
  page: IPage | IFacility | ITraining | IEvent;

  /** Sub Links */
  subLinks?: INavigationLink[] | undefined;
}

/** A link to add to a menu */

export interface INavigationLink extends Entry<INavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navigationLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image: Record<string, any>;

  /** Content */
  content?: Document | undefined;

  /** slug */
  slug: string;
}

/** A basic page for the site */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPersonFields {
  /** Title */
  title: string;

  /** Info */
  info: string;

  /** Image */
  image: Record<string, any>;

  /** Role */
  role:
    | "Committee Member"
    | "Treasurer"
    | "Chairperson"
    | "Paddock Manager"
    | "Member";

  /** Email */
  email?: string | undefined;

  /** Phone */
  phone?: number | undefined;
}

export interface IPerson extends Entry<IPersonFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "person";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITrainingFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image: Record<string, any>;

  /** Content */
  content?: Document | undefined;

  /** slug */
  slug: string;
}

/** A basic page for a training type, such as dressage or basic horsemanship. */

export interface ITraining extends Entry<ITrainingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "training";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "banner"
  | "blog"
  | "card"
  | "cardListing"
  | "carousel"
  | "event"
  | "eventListing"
  | "facility"
  | "facilityListing"
  | "footer"
  | "menu"
  | "navigationLink"
  | "page"
  | "person"
  | "training";

export type IEntry =
  | IBanner
  | IBlog
  | ICard
  | ICardListing
  | ICarousel
  | IEvent
  | IEventListing
  | IFacility
  | IFacilityListing
  | IFooter
  | IMenu
  | INavigationLink
  | IPage
  | IPerson
  | ITraining;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
